imports:
    - { resource: @QcmCoreBundle/Resources/config/core.yml }

qcm_core:
    driver: doctrine/orm
    user_class: Qcm\Bundle\PublicBundle\Entity\User
    classes:
        security:
            model: Qcm\Bundle\PublicBundle\Entity\User
        user:
            model: Qcm\Bundle\PublicBundle\Entity\User
        user_session:
            model: Qcm\Bundle\PublicBundle\Entity\UserSession
        user_session_configuration:
            model: Qcm\Bundle\PublicBundle\Entity\UserSessionConfiguration
        category:
            model: Qcm\Bundle\PublicBundle\Entity\Category
        question:
            model: Qcm\Bundle\PublicBundle\Entity\Question
        answer:
            model: Qcm\Bundle\PublicBundle\Entity\Answer

twig:
    globals:
        qcm_configuration: "@qcm.configuration"
