qcm_public_homepage:
    pattern: /
    defaults:
        _controller: "QcmPublicBundle:Home:index"
        _sylius:
            template: QcmPublicBundle:Question:index.html.twig
            method: getQuestionnaires

qcm_public_question_resource:
    prefix: /questionnaire
    resource: @QcmPublicBundle/Resources/config/routing/question.yml

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"